# Generated by Django 2.0.7 on 2018-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('devid', models.AutoField(primary_key=True, serialize=False, verbose_name='设备ID')),
                ('devip', models.CharField(max_length=16, verbose_name='设备IP地址')),
                ('devname', models.CharField(max_length=32, verbose_name='设备名称')),
                ('devnamealias', models.CharField(max_length=32, verbose_name='设备别名')),
                ('ostype', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统类型')),
                ('cpusize', models.FloatField(blank=True, null=True, verbose_name='CPU大小(GHz)')),
                ('cpucorecount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('memsize', models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)')),
                ('disksize', models.FloatField(blank=True, null=True, verbose_name='磁盘容量(GB)')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房位置')),
                ('devdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='设备描述')),
                ('pdid', models.IntegerField(blank=True, null=True, verbose_name='项目ID')),
                ('customer1', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段1')),
                ('customer2', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段2')),
                ('customer3', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段3')),
                ('customer4', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段4')),
                ('customer5', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段5')),
                ('customer6', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段6')),
                ('customer7', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段7')),
                ('customer8', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段8')),
            ],
            options={
                'db_table': 't_device_info',
                'managed': True,
                'verbose_name_plural': '设备信息表',
                'verbose_name': '设备信息表',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='项目ID')),
                ('projname', models.CharField(max_length=16, verbose_name='项目名称')),
                ('appsystem', models.CharField(max_length=64, unique=True, verbose_name='应用系统')),
                ('projdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='项目描述')),
                ('projcontactname', models.CharField(blank=True, max_length=10, null=True, verbose_name='项目联系人姓名')),
                ('projcontactphone', models.CharField(blank=True, max_length=16, null=True, verbose_name='项目联系人电话')),
                ('projcontactemail', models.EmailField(blank=True, max_length=256, null=True, verbose_name='项目联系人邮箱')),
                ('appcontactname', models.CharField(blank=True, max_length=10, null=True, verbose_name='应用联系人姓名')),
                ('appcontactphone', models.CharField(blank=True, max_length=16, null=True, verbose_name='应用联系人电话')),
                ('appcontactemail', models.EmailField(blank=True, max_length=256, null=True, verbose_name='应用联系人邮箱')),
                ('groupname', models.CharField(blank=True, max_length=32, null=True, verbose_name='小组名称')),
                ('customer1', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段1')),
                ('customer2', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段2')),
                ('customer3', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段3')),
                ('customer4', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段4')),
                ('customer5', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段5')),
            ],
            options={
                'db_table': 't_project_info',
                'verbose_name_plural': '项目信息表',
                'managed': True,
                'verbose_name': '项目信息表',
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False, verbose_name='关系ID')),
                ('localip', models.CharField(max_length=16, verbose_name='本端设备')),
                ('upip', models.CharField(blank=True, max_length=16, null=True, verbose_name='上联设备')),
                ('updesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='上联描述')),
                ('downip', models.CharField(blank=True, max_length=16, null=True, verbose_name='下联设备')),
                ('downdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='下联描述')),
            ],
            options={
                'db_table': 't_relations',
                'managed': True,
                'verbose_name_plural': '关系表',
                'verbose_name': '关系表',
            },
        ),
        migrations.CreateModel(
            name='SoftwareInfo',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, verbose_name='软件ID')),
                ('sip', models.CharField(max_length=16, verbose_name='IP地址')),
                ('sname', models.CharField(max_length=64, verbose_name='软件名称')),
                ('stype', models.CharField(blank=True, max_length=16, null=True, verbose_name='软件类型')),
                ('sport', models.CharField(blank=True, max_length=6, null=True, verbose_name='软件端口')),
                ('sversion', models.CharField(blank=True, max_length=16, null=True, verbose_name='版本')),
                ('spath', models.CharField(blank=True, max_length=128, null=True, verbose_name='路径')),
                ('sdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='软件描述')),
                ('customer1', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段1')),
                ('customer2', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段2')),
                ('customer3', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段3')),
                ('customer4', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段4')),
                ('customer5', models.CharField(blank=True, max_length=256, null=True, verbose_name='自定义字段5')),
            ],
            options={
                'db_table': 't_software_info',
                'managed': True,
                'verbose_name_plural': '软件信息表',
                'verbose_name': '软件信息表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectinfo',
            unique_together={('pid', 'appsystem')},
        ),
    ]
