# Generated by Django 2.0.7 on 2018-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='devnamealias',
            field=models.CharField(max_length=32, unique=True, verbose_name='设备别名'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinfo',
            unique_together={('devid', 'devnamealias')},
        ),
    ]
