# Generated by Django 2.0.7 on 2018-07-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180731_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='devip',
            field=models.CharField(max_length=16, unique=True, verbose_name='设备IP地址'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='devnamealias',
            field=models.CharField(max_length=32, verbose_name='设备别名'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinfo',
            unique_together={('devid', 'devip')},
        ),
    ]
