# Generated by Django 2.0.7 on 2018-07-31 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180731_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='pdid',
        ),
        migrations.RemoveField(
            model_name='relations',
            name='localip',
        ),
        migrations.RemoveField(
            model_name='softwareinfo',
            name='sip',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='pdappsystem',
            field=models.ManyToManyField(blank=True, to='cmdb.ProjectInfo', verbose_name='应用系统'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dpdevip',
            field=models.ManyToManyField(blank=True, to='cmdb.DeviceInfo', verbose_name='设备IP地址'),
        ),
        migrations.AddField(
            model_name='relations',
            name='drdevip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cmdb.DeviceInfo', verbose_name='设备IP地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwareinfo',
            name='dsdevip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cmdb.DeviceInfo', verbose_name='设备IP地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='cpucorecount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='cpusize',
            field=models.FloatField(default=0.0, verbose_name='CPU大小(GHz)'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='devname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='devnamealias',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='设备别名'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='disksize',
            field=models.FloatField(default=0.0, verbose_name='磁盘容量(GB)'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='memsize',
            field=models.IntegerField(default=0, verbose_name='内存大小(GB)'),
        ),
        migrations.AlterModelTable(
            name='deviceinfo',
            table='t_cmdb_device_info',
        ),
        migrations.AlterModelTable(
            name='projectinfo',
            table='t_cmdb_project_info',
        ),
        migrations.AlterModelTable(
            name='relations',
            table='t_cmdb_relations',
        ),
        migrations.AlterModelTable(
            name='softwareinfo',
            table='t_cmdb_software_info',
        ),
    ]
