# Generated by Django 2.0.7 on 2018-08-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180731_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='drdevip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.DeviceInfo', verbose_name='本端设备'),
        ),
        migrations.AddField(
            model_name='relations',
            name='srsname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cmdb.SoftwareInfo',
                                    verbose_name='软件名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwareinfo',
            name='psappsystem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cmdb.ProjectInfo',
                                    verbose_name='应用系统'),
            preserve_default=False,
        ),
    ]
