# Generated by Django 2.0.7 on 2018-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20180801_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='映射编号')),
                ('deviceinfo_id', models.CharField(max_length=16, verbose_name='设备ID')),
                ('projectinfo_id', models.CharField(max_length=16, verbose_name='系统ID')),
            ],
            options={
                'verbose_name': '设备系统映射表',
                'db_table': 't_cmdb_device_info_pdappsystem',
                'managed': False,
                'verbose_name_plural': '设备系统映射表',
            },
        ),
    ]
