# Generated by Django 2.0.7 on 2018-08-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20180807_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='dpdevip',
        ),
    ]
