# Generated by Django 2.0.7 on 2018-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_remove_projectinfo_dpdevip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource_Info',
            fields=[
                ('devid', models.AutoField(primary_key=True, serialize=False, verbose_name='设备ID')),
                ('devip', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='设备IP地址')),
                ('devname', models.CharField(max_length=32, verbose_name='设备名称')),
                ('devnamealias', models.CharField(max_length=32, verbose_name='设备别名')),
                ('ostype', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统')),
                ('devtype', models.CharField(choices=[('VM', '虚拟机'), ('PM', '物理机'), ('Other', '其他')], default='VM', max_length=16, verbose_name='设备类型')),
                ('devstatus', models.CharField(choices=[('online', '在线'), ('offline', '下线'), ('unknown', '未知'), ('fault', '故障'), ('backup', '备用')], default='online', max_length=16, verbose_name='设备状态')),
                ('cpusize', models.FloatField(blank=True, null=True, verbose_name='CPU大小(GHz)')),
                ('cpucorecount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('memsize', models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)')),
                ('disksize', models.FloatField(blank=True, null=True, verbose_name='磁盘容量(GB)')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房位置')),
                ('devdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='设备描述')),
                ('pid', models.CharField(blank=True, max_length=16, null=True, verbose_name='项目ID')),
                ('projname', models.CharField(max_length=16, unique=True, verbose_name='项目名称')),
                ('appsystem', models.CharField(max_length=64, verbose_name='应用系统')),
                ('projdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='项目描述')),
                ('projcontactname', models.CharField(blank=True, max_length=10, null=True, verbose_name='项目联系人姓名')),
                ('projcontactphone', models.CharField(blank=True, max_length=16, null=True, verbose_name='项目联系人电话')),
                ('projcontactemail', models.EmailField(blank=True, max_length=256, null=True, verbose_name='项目联系人邮箱')),
                ('appcontactname', models.CharField(blank=True, max_length=10, null=True, verbose_name='应用联系人姓名')),
                ('appcontactphone', models.CharField(blank=True, max_length=16, null=True, verbose_name='应用联系人电话')),
                ('appcontactemail', models.EmailField(blank=True, max_length=256, null=True, verbose_name='应用联系人邮箱')),
                ('groupname', models.CharField(blank=True, max_length=32, null=True, verbose_name='小组名称')),
                ('sid', models.CharField(blank=True, max_length=16, null=True, verbose_name='软件ID')),
                ('sname', models.CharField(max_length=64, verbose_name='软件名称')),
                ('stype', models.CharField(blank=True, max_length=16, null=True, verbose_name='软件类型')),
                ('sport', models.CharField(blank=True, max_length=6, null=True, verbose_name='软件端口')),
                ('sversion', models.CharField(blank=True, max_length=16, null=True, verbose_name='版本')),
                ('spath', models.CharField(blank=True, max_length=128, null=True, verbose_name='路径')),
                ('sdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='软件描述')),
                ('rid', models.CharField(blank=True, max_length=16, null=True, verbose_name='关系ID')),
                ('upip', models.CharField(blank=True, max_length=16, null=True, verbose_name='上联设备')),
                ('updesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='上联描述')),
                ('downip', models.CharField(blank=True, max_length=16, null=True, verbose_name='下联设备')),
                ('downdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='下联描述')),
            ],
            options={
                'db_table': 'v_resource_info',
                'managed': False,
            },
        ),
    ]
