# Generated by Django 2.0.7 on 2018-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='分类')),
            ],
            options={
                'db_table': 't_repo_category',
                'verbose_name_plural': '分类表',
                'managed': True,
                'verbose_name': '分类表',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('excerpt', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
            ],
            options={
                'db_table': 't_repo_post',
                'managed': True,
                'verbose_name_plural': '文章详情表',
                'verbose_name': '文章详情表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='标签')),
            ],
            options={
                'db_table': 't_repo_tag',
                'verbose_name_plural': '标签表',
                'managed': True,
                'verbose_name': '标签表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name',)},
        ),
    ]
