# Generated by Django 2.0.7 on 2018-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20180731_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='repo/image/default.png', upload_to='repo/image/', verbose_name='分类图片'),
        ),
    ]
