# Generated by Django 2.0.7 on 2018-08-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['-created_time'], 'verbose_name': '文章详情表', 'verbose_name_plural': '文章详情表'},
        ),
    ]
