# Generated by Django 2.0.7 on 2018-08-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20180813_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['-modified_time'], 'verbose_name': '文章详情表', 'verbose_name_plural': '文章详情表'},
        ),
    ]
