# Generated by Django 2.0.7 on 2018-08-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_auto_20180821_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['-created_time'], 'verbose_name': '文章详情表', 'verbose_name_plural': '文章详情表'},
        ),
    ]
